version: '3'
services:
  todocker-db:
    container_name: todocker-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - todocker:/var/lib/postgresql/data
    restart: always
  todocker-back:
    container_name: todocker-back
    build:
      context: ./
      dockerfile: ./apps/back/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: todocker-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

  todocker-front:
    container_name: todocker-front
    build:
      context: ./
      dockerfile: ./apps/front/Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: development
      API_URL: http://localhost:3000
    depends_on:
      - todocker-back


volumes:
  todocker:
